<?php
/**
 * Created by PhpStorm.
 * User: gayan
 * Date: 06/11/13
 * Time: 11:47
 */


?>

<div id="charity-wrapper">
    </br>
    <label> Select Organization :
        <div id="donation-desc">

        </div>
    <?php if (count($this->getAllCharities()) > 1): ?>
            <select id="charity-select" name="charity" class="validate-select">
                <option value="">Select Organization</option>
                <?php foreach ($this->getAllCharities() as $charity): ?>
                    <option value="<?php echo $charity->getId(); ?>"><?php echo $charity->getName(); ?></option>
                <?php endforeach; ?>
            </select>
        </label>
    <?php else: ?>

        <select id="charity-select" name="charity" class="validate-select">
            <?php foreach ($this->getAllCharities() as $charity): ?>
                <option value="<?php echo $charity->getId(); ?>"><?php echo $charity->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    <?php endif; ?>

</div>

<script type="text/javascript">
    var amounts = <?php echo $this->getCharityAmountByProductId();?>;
    document.observe("dom:loaded", function () {
        $$('div.price-box')[0].insert($('charity-wrapper'));

        //On change charity dropdown
        $("charity-select").observe('change', function () {
            $('donation-desc').innerHTML = "";
            if ($("charity-select").value != "") {
                if (amounts[$("charity-select").value] != undefined) {
                    $('donation-desc').innerHTML = amounts[$("charity-select").value];
                }
            }
        })
        fireEvent($("charity-select"), 'change');
    });
</script>