<?php
/**
 * Created by PhpStorm.
 * User: gayan
 * Date: 06/11/13
 * Time: 11:47
 */
?>

<div id="charity-wrapper">
    </br>
    <label> Select Charity :
        <div id="donation-desc">

        </div>
        <select id="charity-select" name="charity">
            <option value="">Select Charity</option>
            <?php foreach ($this->getAllCharities() as $charity): ?>
                <option value="<?php echo $charity->getId(); ?>"><?php echo $charity->getName(); ?></option>
            <?php endforeach; ?>
        </select>
    </label>
</div>

<script type="text/javascript">
    var amounts = <?php echo $this->getCharityAmountByProductId();?>;
    document.observe("dom:loaded", function () {
        $$('div.price-box')[0].insert($('charity-wrapper'));

        //On change charity dropdown
        $("charity-select").observe('change', function () {
            $('donation-desc').innerHTML = "";
            if ($("charity-select").value != "") {
                if (amounts[$("charity-select").value] != undefined) {
                    $('donation-desc').innerHTML = amounts[$("charity-select").value];
                }
            }
        })

    });
</script>