<?php
/**
 * Created by PhpStorm.
 * User: gayan
 * Date: 15/11/13
 * Time: 13:07
 */

if (Mage::getSingleton('core/session')->getCharity()) {
    $array = Mage::getSingleton('core/session')->getCharity();
    $ar = array();
    foreach($array as $row){
        $ar[$row["org_id"]]["total"] += $row["total"];
        $ar[$row["org_id"]]["org_name"] = $row["org_name"];
    }

}
?>
<?php foreach($ar as $key=>$summary):?>
    <tr class="charity">
        <td <?php echo $this->getLabelProperties()?>>
                <strong><?php echo $this->helper('sales')->__('Total Donation for '.$summary["org_name"]) ?></strong>
        </td>
        <td <?php echo $this->getValueProperties()?>>
                <?php echo $this->formatValue($summary["total"]) ?>
        </td>
    </tr>
<?php endforeach;?>

<?php foreach ($this->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $this->getChildHtml($_total->getBlockName(), false); ?>
    <?php else:?>
        <tr class="<?php echo $_code?>">
            <td <?php echo $this->getLabelProperties()?>>
                <?php if ($_total->getStrong()):?>
                    <strong><?php echo $this->escapeHtml($_total->getLabel());?></strong>
                <?php else:?>
                    <?php echo $this->escapeHtml($_total->getLabel());?>
                <?php endif?>
            </td>
            <td <?php echo $this->getValueProperties()?>>
                <?php if ($_total->getStrong()):?>
                    <strong><?php echo $this->formatValue($_total) ?></strong>
                <?php else:?>
                    <?php echo $this->formatValue($_total) ?>
                <?php endif?>
            </td>
        </tr>
    <?php endif?>
<?php endforeach?>