<?php
/**
 * Created by PhpStorm.
 * User: gayan
 * Date: 11/11/13
 * Time: 23:11
 */
?>


<?php foreach($list  as $row):?>
    <div class="organizatoin-widget <?php echo $row->getId();?>">
        <div class="organization-name"><?php echo $row->getName();?></div>
        <div class="organization-website">
            <?php if($row->getWebsite() != ""):?>
                <a href="<?php echo $row->getWebsite();?>">
                    <?php echo $row->getWebsite();?>
                </a>
            <?php endif;?>
            <?php if($row->getImage() != ""):?>
                <img class='organization-logo' src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $row->getImage();?>"/>
            <?php endif;?>
        </div>
        <div class="organization-total"><?php echo Mage::helper('core')->currency($row->getData('sum'), true, false);?></div>
    </div>
<?php endforeach;?>